using LawSearch_API.Utils;
using LawSearch_Core.Interfaces;
using LawSearch_Core.Models;
using LawSearch_Core.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Data;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace LawSearch_API.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class LawDocController : ControllerBase
    {
        private readonly ILawDocService lawDocService;
        private readonly ILogger<LawDocController> logger;

        public LawDocController(ILawDocService lawDocService, ILogger<LawDocController> logger)
        {
            this.lawDocService = lawDocService;
            this.logger = logger;
        }

        [HttpGet, Authorize]
        public APIResult GetListLaw()
        {
            logger.LogInformation(Request.Method + " " + Request.Scheme + "://" + Request.Host + Request.Path);
            List<LawDoc> dtResult = lawDocService.GetListLawDoc();
            APIResult rs = new();
            return rs.Success(dtResult);
        }

        [HttpGet("[action]"), Authorize]
        public APIResult GetLawHTML(int id)
        {
            logger.LogInformation(Request.Method + " " + Request.Scheme + "://" + Request.Host + Request.Path);
            DataTable dtResult = lawDocService.GetLawHTML(id);
            APIResult rs = new();
            return rs.Success(dtResult);
        }

        [HttpPost, Authorize(Roles = "Admin")]
        public APIResult PostLaw([FromForm] LawImport lawImport)
        {
            logger.LogInformation(Request.Method + " " + Request.Scheme + "://" + Request.Host + Request.Path + Request.QueryString);
            lawDocService.ImportLaw(lawImport.Name, lawImport.Content);
            APIResult rs = new();

            return rs.MessageSuccess("Import văn bản luật thành công");
        }

        [HttpDelete, Authorize(Roles = "Admin")]
        public async Task<APIResult> DeleteLawDocument([BindRequired] int id)
        {
            logger.LogInformation(Request.Method + " " + Request.Scheme + "://" + Request.Host + Request.Path + Request.QueryString);
            lawDocService.DeleteLawDocument(id);
            APIResult rs = new();
            return rs.MessageSuccess("Delete law document success");
        }

        [HttpPost("[action]"), Authorize(Roles = "Admin")]
        public APIResult AddLawHTML([FromForm] LawHTML lawHTML)
        {
            logger.LogInformation(Request.Method + " " + Request.Scheme + "://" + Request.Host + Request.Path + Request.QueryString);
            lawDocService.AddLawHTML(lawHTML.LawID, lawHTML.contentHTML);
            APIResult rs = new();
            return rs.MessageSuccess("Import LawHTML success !");
        }

        [HttpPost("[action]"), Authorize(Roles = "Admin")]
        public APIResult UpdateLawHTML([FromForm] LawHTML lawHTML)
        {
            logger.LogInformation(Request.Method + " " + Request.Scheme + "://" + Request.Host + Request.Path + Request.QueryString);
            lawDocService.UpdateLawHTML(lawHTML.LawID, lawHTML.contentHTML);
            APIResult rs = new();
            return rs.MessageSuccess("Update LawHTML success !");
        }

        [HttpPost("[action]"), Authorize(Roles = "Admin")]
        public async Task<APIResult> AutoGenerateData([BindRequired] int LawID)
        {
            logger.LogInformation(Request.Method + " " + Request.Scheme + "://" + Request.Host + Request.Path);
            await lawDocService.AutoGenerateData(LawID);
            APIResult result = new APIResult();
            return result.MessageSuccess("Generate success!");
        }
    }
}
